---
title: "Prepare .mat for aroval GLM"
output: html_notebook
---

# Load library and define initial variables
```{r, message=F}
library(tidyverse)

subs_file <- "/data00/leonardo/RSA/sub_list.txt"
subs <- sprintf("%02d",readLines(subs_file) %>% as.numeric)

model="aroval"
movie_duration = 1.5 # (seconds)

# read ratings and zeropad the sub number
# remove the onset_sec - the onset in the out-of-scanner session
# not to generate confusion with the onset_sec column in the 
# onset.csv file (onsets inside the scanner)
ratings <- read_csv(
  paste0(
    "/data00/leonardo/RSA/analyses/RATINGS", "/", model, "_ratings.csv"
  )
)

ratings

nRuns = 8
runs <- 1:nRuns

runs

# In the posttask movies were presented only once, but we need to create .mat files
# for 8 runs, therefore we cp/paste all the rows 8 times
ratings_all_runs <- runs %>% map_dfr(
  ~ ratings %>% mutate(run = .x) %>% relocate(sub,run)
)

# # test ratings_all_runs with the following
# ratings_all_runs %>% 
#   # group_by(high_low_code) %>%
#   count(sub, high_low_code, name = "n_runs") %>% 
#   group_split(sub);

```


# Inner join the fmri log and the rating by high_low_code 
For each sub and run separately, so that we can then purrr the function

```{r}

# variable setting for testing ONLY - to be removed in the next purrr
sub_id = subs[1]
run_id = 1
orig_csv_root = "/data00/leonardo/RSA/raw_data"
dest = paste0("/data00/leonardo/RSA/prep_data/sub-", sub_id, "/fmri/", model)


read_onsets_write_mat <- function(sub_id, run_id, dest) {
  
  # paste0("Writing emotion_rating mat files for sub ",sub_id, " run ", run_id,"\n") %>% cat
  
  sub_onsets_file <- paste0(orig_csv_root,
      "/sub-", sub_id,
      "/onsets/sub-", sub_id, "_onset_run",run_id,".csv")
  
  # NB: the sub in fmri_log is read from a csv and assigned to dbl for numbers
  # above 09, however I need to join it with the sub in ratings_all_runs
  # which is a char, therefore I need to change the datatype of that column
  fmri_log <- read_csv(sub_onsets_file, progress = F) %>% suppressMessages() %>% 
    mutate(sub = as.character(sub))
  
  joined_ratings_fmri_logs <- ratings_all_runs %>% 
    filter(sub == sub_id, run == run_id) %>% 
    select(sub, run, starts_with("r_"), high_low_code) %>% 
    inner_join(fmri_log, by = c("sub","run","high_low_code"))

    
    # --------- allMovies + [model] parametric modulation ------------------------
  
  # select onset_sec, duration and intensity to prepare the .mat file
  mat_4_feat <- joined_ratings_fmri_logs %>% 
    mutate(duration = movie_duration) %>% 
    select(onset_sec, duration, starts_with("r_")) %>% 
    # remove the mean of all predictors starting with "r_" (required for parametric modulation)
    mutate(across(starts_with("r_"), ~ . - mean(.x, na.rm = TRUE))) %>% 
    arrange(onset_sec)
  
  for (aroval in c("arousal","valence")) {
    mat_one_predictor <- mat_4_feat %>% 
      select(onset_sec, duration, paste0("r_", aroval))
    
    mat_path <- paste0(dest, "/sub-", sub_id, "_run-", run_id, "_", aroval, "_rating.mat")
    # print(mat_path)
    
    write_tsv(mat_one_predictor, col_names = FALSE, mat_path)
  }
  
  # create the mat for allMovies
  mat_allMovies <- mat_4_feat %>% 
    select(onset_sec, duration) %>% 
    mutate(allMovies_intensity = 1)
  
  mat_allMovies_path <- paste0(dest, "/sub-", sub_id, "_run-", run_id, "_allMovies", ".mat")
  write_tsv(mat_allMovies, col_names = FALSE, mat_allMovies_path)
  
    # --------- allMovies + [model] parametric modulation ------------------------  
  
}



# use the following with one sub to test that same movies have
# same rating across runs but different onset_sec
runs %>% walk(~ read_onsets_write_mat(sub_id = subs[1], run_id = .x, dest = dest))

```


# Loops across subs and runs
I use a `for` construct for subjects since two nested `map` can be difficult to read 
```{r, message=F}

for (sub_id in subs) {
  
  orig_csv_root = "/data00/leonardo/RSA/raw_data"
  dest = paste0("/data00/leonardo/RSA/prep_data/sub-", sub_id, "/fmri/", model)
  
  # create the dir where all the mat files (and the stats.feat) will be stored
  if (!dir.exists(dest)) {dir.create(dest)} else paste0(dest, " exists")
  paste0("Creating .mat files for sub", sub_id, " in ", dest) %>% print
  
  # write all .mat files (one for each run) for that sub
  runs %>% walk(~ read_onsets_write_mat(sub = sub_id, run = .x, dest = dest))
}

```


























