---
title: "R Notebook"
output: html_notebook
---

Here we experiment with some dimred methods to assess the consistency of the ratings.

NB: umap requires reticulate. We need to install a version of reticulate which does not require `RcppTOML` (v1.4)
`remotes::install_version("reticulate", version = "1.4")`


# Load the ratings for all subs
```{r, message=FALSE}
library(tidyverse)
library(proxy)
# pr_DB$get_entries() 
# summary(pr_DB)

bd="/data00/leonardo/RSA/analyses"

ratings_type <- "emotion"
bd_ratings = paste0(bd,"/RATINGS")
ratings_path <- paste0(bd_ratings,"/",ratings_type,"_ratings.csv")
rats <- read_csv(ratings_path)

# arrange by emotion to have a reference
rats <- rats %>% arrange(emotion)

subs_file <- "/data00/leonardo/RSA/sub_list.txt"
subs <- sprintf("%02d",readLines(subs_file) %>% as.numeric)

# plot_heatmap(D %>% as.matrix)
plot_heatmap <- function(M) {
  heatmap(M, Rowv = NA, Colv = NA, symm=T, revC = T)
}
```


# Subject exclusion
```{r}

# # If you want to select subs, do it here
# subs_to_exclude <- c(7,34,24,10,16,31,30,27,05,21,14) %>% as.character()
# subs <- subs[!subs %in% subs_to_exclude]
# rats <- rats %>% 
#   filter(sub %in% subs)
# 
# subs

```




# List the available metrics
```{r}
summary(pr_DB)
```



```{r}

labels <- rats$emotion
high_low <- str_extract(rats$high_low_code, "high|low")
length(labels)

summary(pr_DB)
dist_method <- "euclidean"

tic()
D <- rats %>% 
  filter(sub %in% subs) %>%
  arrange(emotion) %>% 
  select(starts_with("r_")) %>% 
  dist(method = dist_method) %>% 
  as.matrix
toc()

rownames(D) <- colnames(D) <- labels

dim(D)

plot_heatmap(D %>% as.matrix)

# # replacing the NAs which come out mostly from neutral movies, which have
# # mostly scores at 0 across all emotion rating
#
# rats %>%
#   mutate(r_sum = rowSums(select(., starts_with("r_")), na.rm = TRUE)) %>% 
#   select(video, r_sum) %>% 
#   filter(r_sum == 0)


D[is.na(D)] <- 0
# sum(is.na(D)) / length(D)
# sum(is.infinite(D)) / length(D)

```


# SVD and plot
```{r}

# Perform SVD
svd_result <- svd(D)

# Extract the first two eigenvectors (U matrix in SVD)
U <- svd_result$u[,1:3]
S <- svd_result$d[1:3] %>% diag
US <- U %*% S

# define which lowdim components to use
lowdim_x = 2
lowdim_y = 3
svd_lowdim <- data.frame(pc_x = US[,lowdim_x], pc_y = US[,lowdim_y], labels, high_low)

paletta <- c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3", "#FF7F00", "#FFFF33", "#A65628")

ggplot(svd_lowdim, aes(x = pc_x, y = pc_y, color = labels, shape = high_low)) +
  geom_point(size = 3, alpha = 0.7) +  # Open circles for points
  scale_color_manual(values = paletta) +
  scale_shape_manual(values = c(1, 3)) +  # Assign specific shapes
  labs(title = "UMAP Projection", x = paste0("lowdim ",lowdim_x), y = paste0("lowdim ",lowdim_y)) +
  theme_minimal() +
  guides(color = guide_legend(override.aes = list(shape = 16)))  # Filled circles in the legend


```



```{r, warning=FALSE}

library(umap)
# tunings here : https://cran.r-project.org/web/packages/umap/vignettes/umap.html

# # Perform UMAP
umap_result <- umap::umap(D, input="dist", n_components=5)

# define which lowdim components to use
lowdim_x = 2
lowdim_y = 3
umap_lowdim <- data.frame(UMAP1 = umap_result$layout[,lowdim_x], UMAP2 = umap_result$layout[,lowdim_y], labels, high_low)

paletta <- c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3", "#FF7F00", "#FFFF33", "#A65628")

ggplot(umap_lowdim, aes(x = UMAP1, y = UMAP2, color = labels, shape = high_low)) +
  geom_point(size = 4, alpha = 0.7) +  # Open circles for points
  scale_color_manual(values = paletta) +
  scale_shape_manual(values = c(1, 3)) +  # Assign specific shapes
  labs(title = "UMAP Projection", x = paste0("lowdim ",lowdim_x), y = paste0("lowdim ",lowdim_y)) +
  theme_minimal() +
  guides(color = guide_legend(override.aes = list(shape = 16)))  # Filled circles in the legend


```




























