---
title: "Generate design.mat"
author: "LC"
date: "2024-11-29"
output: html_document
---

```{r}
library(tidyverse)

# NB: remember to change the number of ALLMOVIES cope (to be removed)
#     according to the model! For emotion, it is cope 7

model="emotion"
bd <- paste0("/data00/leonardo/RSA/analyses/parametric_modulation/",model)

subs_file <- "/data00/leonardo/RSA/sub_list.txt"
subs <- sprintf("%02d",readLines(subs_file) %>% as.numeric)
```


# Generate df with file_path of the cope1.nii.gz images
```{r}

bd_2nd_level = paste0(bd,"/results/2nd_level")

df <- list.files(
  bd_2nd_level, 
  pattern = "^cope1.nii.gz", recursive = T
) %>% 
  
  # read all the *cope1.nii.gz in a tibble
  as_tibble() %>% 
  rename(file_path = value) %>% 
  
  # full path of file_path
  mutate(file_path = paste0(bd_2nd_level,"/",file_path)) %>%
  
  # add columns for sub and for cope#
  mutate(
    sub = str_extract(file_path, paste(subs, collapse = "|")),
    cope = str_extract(file_path, "cope\\d+\\.feat") %>% str_remove_all("[^\\d]")
  ) %>% 
  
  # REMOVE ALLMOVIES COPE (number 7)
  filter(cope != 7)
  

df
  
```

# Write the list of files to pass to the Feat GUI
```{r}

writeLines(
  df$file_path,
  con = paste0(bd,"/results/list_cope_nii_gz.txt")
)


```


# Generate design.mat
```{r}

n_subs = length(subs)
n_copes = length(unique(df$cope))

# create design.mat in a ff dataframe
ff <- df %>% select(sub,cope)

for (i in 1:n_copes) {
  ev_column <- paste0("EV", i)  # Create the name for the EV column (e.g., EV1, EV2, etc.)
  
  # Add the column where the cope number equals i will be 1, others will be 0
  ff <- ff %>%
    mutate(!!ev_column := ifelse(cope == i, 1, 0))
}

ff
```



# Viz the design matrix
```{r}

ff_matrix <- ff %>%
  # arrange(cope) %>%
  mutate(across(everything(), as.numeric)) %>%
  mutate(row_label = paste0("s",sub,"_cope",cope)) %>% 
  select(-sub) %>% 
  column_to_rownames("row_label") %>% 
  as.matrix()

# Plot the heatmap (after reversing the order of the rows)
heatmap(ff_matrix[nrow(ff_matrix):1, ], Rowv = NA, Colv = NA)

```

# Write the matrix

```{r}

df2write <- ff %>%
  mutate(row_label = paste0("s",sub,"_cope",cope)) %>% 
  relocate(row_label) %>% 
  select(!c(sub,cope)) %>% 
  column_to_rownames("row_label") %>% 
  mutate(across(everything(), as.numeric)) %>%
  as.matrix

df2write

write.table(
  df2write,
  file = paste0(bd,"/results/design.mat"),
  sep = " ",
  col.names = FALSE,
  row.names = FALSE,
  quote = FALSE
)

```


















