---
title: "Prepare .mat for emotion GLM"
output: html_notebook
---

# Load library and define initial variables
```{r, message=F}
library(tidyverse)

subs_file <- "/data00/leonardo/RSA/sub_list.txt"
subs <- sprintf("%02d",readLines(subs_file) %>% as.numeric)

model="one_ev_per_movie_minus_neutral"
movie_duration = 1.5 # (seconds)

nRuns = 8
runs <- as.character(1:nRuns)
```


# Reading onset.csv file, prepare and write the .mat files

```{r}

# --------------------- ONLY for developing the fn below ----------------------
sub_id = subs[1]
run_id = 1

orig_csv_root = "/data00/leonardo/RSA/raw_data"
dest = paste0("/data00/leonardo/RSA/prep_data/sub-", sub_id, "/fmri/", model)
# -----------------------------------------------------------------------------



read_onsets_write_mat <- function(sub_id, run_id, dest) {

  sub_onsets_file <- paste0(orig_csv_root,
       "/sub-", sub_id,
       "/onsets/sub-", sub_id, "_onset_run",run_id,".csv")
  
  # read onset file and add duration and intensity (constants) columns for mat file
  # NB here the "intensity" is not the high/low, it's the one for the 3-col mat file
  df <- read_csv(sub_onsets_file, progress = F) %>% suppressMessages() %>% 
    mutate(duration = movie_duration, intensity = 1)
  
  # select the 3 columns : onset_sec, duration, intensity
  # and generate the filename where the emotion code is replaced
  # by the emotion name spelled out
  df_4_mat <- df %>% 
    select(high_low_code, onset_sec, duration, intensity) %>% 
    separate(high_low_code, into = c("actor", "emotion_code", "high_low"), sep = "_") %>% 
    mutate(emotion_code = case_when(
     emotion_code == "A" ~ "Anger",
     emotion_code == "D" ~ "Disgust",
     emotion_code == "F" ~ "Fear",
     emotion_code == "H" ~ "Happy",
     emotion_code == "N" ~ "Neutral",
     emotion_code == "P" ~ "Pain",
     emotion_code == "S" ~ "Sad",
     TRUE ~ as.character(emotion_code)  # If none of the above, keep the original value
    )) %>% 
    mutate(mat_filename = paste(actor,emotion_code,high_low,sep = "_")) %>% 
    select(mat_filename, onset_sec, duration, intensity)
  
  # Write every mat file (in this case it will be one line per mat file)
  for (movie in df_4_mat$mat_filename) {
    
    mat_file_path <- paste0(dest,"/sub-",sub_id,"_run-",run_id,"_",movie,".mat")
    # paste0(mat_file_path,"\n") %>% cat
    
    mat_file_3_cols <- df_4_mat %>%
      filter(mat_filename == movie) %>%
      select(!mat_filename) %>%
      write_tsv(col_names = FALSE, mat_file_path)
    
  }
}


# # example use below
runs %>% walk(~ read_onsets_write_mat(sub_id = subs[1], run_id = .x, dest = dest))
# # You can then check in the dir the correct numba of files with the following 
# # bash code. There are 56 movies per run: 6+1 movies * 4 actors * 2 high/low
# for i in $(seq 8); do echo run ${i} `ls sub*run-${i}*.mat | wc -l`; done

```



# Loops across subs and runs
I use a `for` construct for subjects since two nested `map` can be difficult to read 
```{r, message=F}

for (sub_id in subs) {
  
  # e.g. /data00/leonardo/RSA/raw_data/sub-02/onsets
  orig_csv_root = "/data00/leonardo/RSA/raw_data"
  dest = paste0("/data00/leonardo/RSA/prep_data/sub-", sub_id, "/fmri/", model)
  
  # create the dir where all the mat files (and the stats.feat) will be stored
  if (!dir.exists(dest)) {dir.create(dest)} else paste0(dest, " exists")
  paste0("Creating .mat files for sub", sub_id, " in ", dest) %>% print
  
  # write all .mat files (one for each run) for that sub
  runs %>% walk(~ read_onsets_write_mat(sub_id = sub_id, run_id = .x, dest = dest))
}

```



Just to check that there are exactly 56 mat files per sub per run, run the following bash script
```{bash}

root="/data00/leonardo/RSA/prep_data"

for sub in `ls ${root}`; do

mat_path=${root}/${sub}/fmri/one_ev_per_movie

echo ${mat_path}

  for i in $(seq 8); do
    echo run ${i} `ls ${mat_path}/*run-${i}*.mat | wc -l`;
  done

done

```




```{r}

# Prepare the list_numba_movies.txt which will be used by 02_do_first_level_stats.sh
# For this you just need to load the onset of one sub/run. 
# The movie/cope number relates to the alphabetical order of the movies with the high/low code and the emotion name spelled out, therefore is the same across all subs/runs

sub_id = subs[1]
run_id = 1

orig_csv_root = "/data00/leonardo/RSA/raw_data"

sub_onsets_file <- paste0(orig_csv_root,"/sub-", sub_id,
       "/onsets/sub-", sub_id, "_onset_run",run_id,".csv")

ff <- read_csv(sub_onsets_file, progress = F) %>% suppressMessages()

list_numba_movies <- ff %>%
  select(high_low_code, movie_cope_number) %>% 
  separate(high_low_code, into = c("actor", "emotion_code", "high_low"), sep = "_") %>% 
    mutate(emotion_code = case_when(
     emotion_code == "A" ~ "Anger",
     emotion_code == "D" ~ "Disgust",
     emotion_code == "F" ~ "Fear",
     emotion_code == "H" ~ "Happy",
     emotion_code == "N" ~ "Neutral",
     emotion_code == "P" ~ "Pain",
     emotion_code == "S" ~ "Sad",
     TRUE ~ as.character(emotion_code)  # If none of the above, keep the original value
    )) %>% 
  mutate(movie_name = paste(actor,emotion_code,high_low,sep = "_")) %>% 
  select(movie_cope_number, movie_name) %>% 
  arrange(movie_cope_number)

list_numba_movies

write_tsv(list_numba_movies, "list_numba_movies.txt", col_names = FALSE)

```
















