---
title: "sketchbook"
author: "LC"
date: "2024-08-19"
output: html_document
---

```{r}
library(tidyverse)
dir("results_RSA_ROI/")
```


```{r}
load("results_RSA_ROI/Yeo7_EHLP_RN.RData")
```


```{r}
mean_RDMs_fmri$data
```

```{r}
mean_RDMs_rats %>% as.matrix %>% cor

plot(mean_RDMs_rats$rdm_emotion ~ mean_RDMs_rats$rdm_valence)
```


# One sample t-test for > 0 for every column of a df
```{r, message=FALSE}
library(tidyverse)
library(ggstatsplot)

n = 100

df <- tibble(
  arousal = rnorm(n, 0, 1),
  aroval = rnorm(n, 0.1, 1),
  emotion = rnorm(n, 0.5, 1)
)

# df %>% 
#   reframe(across(everything(), ~mean(.x)))

# Perform one-sample t-test and extract p-values
df %>%
  reframe(across(everything(), ~ t.test(.x, mu = 0, alternative = "greater")$p.value))

p <- df %>% 
  pivot_longer(cols = everything(), names_to = "cols", values_to = "value") %>% 
  ggwithinstats(
    x = cols,
    y = value,
    type = "np",
    results.subtitle = TRUE,
  )

# extract_stats(p)

p

```

```{r}
library(infer)
library(broom)
library(gt)
library(gtsummary)

model <- function(vals) infer::t_test(vals, response = value, alternative = "greater")

df %>% 
  pivot_longer(cols = everything(), names_to = "models", values_to = "value") %>% 
  group_by(models) %>% nest %>% 
  mutate(stats = data %>% map(~ model(.x)) ) %>% 
  unnest(cols = stats) %>% 
  select(models, statistic, t_df, p_value)


library(gt)
library(broom)

model <- function(val) t.test(val, mu = 0, alternative = "two.sided")  # greater or two.sided

df %>% 
  map_dfr(~ broom::tidy(model(.x)), .id = "rsa_model") %>%
  mutate(t = paste0("t=",round(statistic, 2)) ) %>% 
  mutate(p = ifelse(p.value >= 0.001, paste0("p = ",round(p.value,2) ), "p < 0.001")) %>% 
  mutate(res = paste0(t,", ",p)) %>%
  select(rsa_model, res) %>% 
  pivot_wider(names_from = rsa_model, values_from = res) %>% 
  gt() %>% 
  tab_options(table.font.size = px(14)) %>% 
  tab_style(style = cell_text(style = "italic"), locations = cells_body()) %>% 
  cols_width(everything() ~ px(300))

# scales::pvalue(p.value)
  
```



```{r}
results <- df %>%
  summarise(across(everything(), ~ tidy(t.test(.)))) %>%
  pivot_longer(everything(), names_to = "Variable", values_to = "TTest") %>%
  unnest(TTest)

# Create a table using gtsummary
results_table <- results %>%
  select(Variable, estimate, statistic, p.value, conf.low, conf.high) %>%
  mutate(
    p.value = scales::pvalue(p.value),
    estimate = sprintf("%.2f", estimate),
    statistic = sprintf("%.2f", statistic),
    conf.low = sprintf("%.2f", conf.low),
    conf.high = sprintf("%.2f", conf.high)
  ) %>%
  gt() %>%
  tab_header(title = "One-Sample T-Test Results") %>%
  fmt_number(columns = vars(estimate, statistic, p.value, conf.low, conf.high), decimals = 2)

# Print the table
results_table

```



# papaya viz
```{r}

bd="/data00/leonardo/RSA/analyses"
bd_atlases = paste0(bd,"/ROIS_REPO")
bd_results = paste0(bd,"/RSA_ROI_APP/results_RSA_ROI")

Dummy <- paste0(bd,"/ROIS_REPO/Dummy.nii.gz")
MNI <- paste0(bd,"/ROIS_REPO/MNI152_T1_2mm_brain.nii.gz")

# papaya display volumes
papaya_display <- function(model) {
  
  rsa_results_nii <- paste0(bd,"/RSA_ROI_APP/results_RSA_ROI/tmp_",model,".nii.gz")
  rsa_results_nii <- paste0(bd_atlases,"/",atlas_filename)
  
  papaya(
    c(Dummy, MNI, rsa_results_nii),
    options = list(
      papayaOptions(alpha = 1, lut = "Grayscale"),
      papayaOptions(alpha = 0.5, lut = "Grayscale"),
      papayaOptions(alpha = 0.6, lut = "Red Overlay", min = 0.1, max = 0.25)
    ),
    interpolation = FALSE,
    orthogonal = TRUE,
    hide_controls = TRUE,
    title = model
  )
}

model="emotion"
papaya_display(model)

```



# read XML of juelich
```{r}

library(xml2)

jubrain_XML <- "/data00/leonardo/RSA/analyses/ROIS_REPO/jubrain/orig/maximum-probability-maps_MPMs_207-areas/JulichBrainAtlas_3.1_207areas_MPM_rh_MNI152.xml"

# Read the XML file
xml_file <- read_xml(jubrain_XML)

# Extract all Structure nodes
structures <- xml_find_all(xml_file, "//Structure")

# Create a dataframe with grayvalue and name
df <- tibble(
  grayvalue = xml_attr(structures, "grayvalue"),
  name = xml_text(structures)
)

# Display the dataframe
print(df)

library(reactable)
reactable(df)


reactable(
  df, 
  style = list(fontFamily = "Arial narrow", fontSize = "13px")
)

```


## ggplot themes
```{r}

library(ggstatsplot)
library(ggdark)


ggwithinstats(
  data = bugs_long,
  x = condition,
  y = desire,
  type = "np",
  results.subtitle = FALSE
) +
  ggdark::dark_theme_dark() +
  theme(legend.position = "none")
  
  
```


# RSA between regions
# "/data00/leonardo/RSA/analyses/RSA_ROI_APP/sketchbook.Rmd"

```{r}
library(tidyverse)


load("results_RSA_ROI/Yeo17_EHLP_RN_N14.RData")

df <- mean_RDMs_fmri

df

df %>% 
  unnest() %>% 
  group_split()

ff <- df %>% 
  unnest(c("data")) %>% 
  pivot_wider(names_from = "roi", values_from = "mean_tril") %>% 
  unnest()


CC <- cor(ff, method = "pearson")

CC %>% heatmap

library(uwot)

u <- umap(1-CC)

pcs <- list(u[,1], u[,2])


library(plotly)


```


# Plot options on ggwithinstats
```{r, message=FALSE}
library(tidyverse)
library(ggstatsplot)

n = 26

df <- tibble(
  arousal = rnorm(n, 0, 1),
  aroval = rnorm(n, 0.1, 1),
  emotion = rnorm(n, 0.5, 1)
)


df %>% 
  pivot_longer(cols = everything(), names_to = "cols", values_to = "value") %>% 
  ggwithinstats(
        x = cols,
        y = value,
        type = "p",
        results.subtitle = FALSE,
        centrality.label.args = list(size = 10),
        point.args = list(size=5, alpha=0.5)
      ) + 
      theme(
        axis.title = element_blank(),
        axis.text = element_text(size = 28),
        axis.title.y.right = element_blank()
      ) +
      ggplot2::scale_x_discrete(labels = ~ gsub(" \\(n=.*\\)", "", .))

```



```{r}
library(shiny)
library(tidyverse)
library(ggstatsplot)

# Generate data
n = 100
df <- tibble(
  arousal = rnorm(n, 0, 1),
  aroval = rnorm(n, 0.1, 1),
  emotion = rnorm(n, 0.5, 1)
)

# Define UI
ui <- fluidPage(
  titlePanel("Shiny Plot with Download"),
  plotOutput("plot"),
  downloadButton("downloadPlot", "Download Plot as PDF")
)

# Define Server
server <- function(input, output) {
  
  # Create the plot
  myplot <- reactive({
    df %>% 
      pivot_longer(cols = everything(), names_to = "cols", values_to = "value") %>% 
      ggwithinstats(
        x = cols,
        y = value,
        type = "p",
        results.subtitle = FALSE,
        centrality.label.args = list(size = 10),
        point.args = list(size=5, alpha=0.5)
      ) + 
      theme(
        axis.title = element_blank(),
        axis.text = element_text(size = 28),
        axis.title.y.right = element_blank()
      ) +
        ggplot2::scale_x_discrete(labels = ~ gsub(" \\(n=.*\\)", "", .))

  })
  
  # Render plot in UI
  output$plot <- renderPlot({
    myplot()
  })
  
  # Download handler
  output$downloadPlot <- downloadHandler(
    filename = function() { "myplot.pdf" },
    content = function(file) {
      ggsave(file, plot = myplot(), width = 8, height = 6)
    }
  )
}

# Run the Shiny app
shinyApp(ui, server)

```


# Working on plot aesthetics
```{r}

library(tidyverse)
library(ggstatsplot)

n = 100

df <- tibble(
  arousal = rnorm(n, 0, 1),
  aroval = rnorm(n, 0.1, 1),
  emotion = rnorm(n, 0.5, 1)
) %>% 
  pivot_longer(cols = everything(), names_to = "cols", values_to = "value")


df %>% 
  ggwithinstats(
    x = cols,
    y = value,
    type = "np",
    results.subtitle = TRUE,
  )


```

```{r}
library(ggplot2) # Make sure ggplot2 is loaded

library(bslib)

library(showtext)
font_add_google("Montserrat")
showtext_auto()


roi_numba=5
MCP_correction_method = "none"
ttest_type = "p"

df <- df %>% 
  mutate(model=cols)

df %>%
  ggwithinstats(
  x = model, y = value,
  type = ttest_type,   # p, np, r, b
  title = paste0("roi ", roi_numba),
  results.subtitle = TRUE,
  bf.message = FALSE,
  ggsignif.args = list(textsize = 3, tip_length = 0.01),
  p.adjust.method = MCP_correction_method,
  centrality.label.args = list(size  = 5),
  point.path = FALSE
  ) +
  labs(y = "RSA", x = NULL) +
  theme(
    text = element_text(size = 15, family = "Coming Soon"),
    axis.text = element_text(size = 16),
    axis.title.y = element_text(size = 16),   # Only affects y-axis title
    axis.title.x = element_blank(),           # Hides x-axis title
    plot.title = element_text(size = 18, family = "Coming Soon"),
    plot.subtitle = element_text(size = 15, family = "Coming Soon"), # Add margin
  )
```






















